### ISSUE TITLE
Missing latest release

### ISSUE THREAD

**Issue by Krejdom** [bottlepy/bottle-sqlite#12]
Hi, could you please upload the latest version of sources to PyPI (https://pypi.python.org/pypi/bottle-sqlite)?
It would be also great, if you could create the release here on GitHub.

**Comment by avelino** [comment]
@defnull I don't have access to this package on pypi, can I add it?

**Comment by defnull** [comment]
@avelino you are now :)

**Comment by avelino** [comment]
@Krejdom sent new release to pypi.

**Comment by Krejdom** [comment]
@avelino Thanks. Is there any reason why you excluded README.rst file?
